const staticValues = [
  { id: 'root', value: '2022 - الخطة الشجرية لهندسة الحاسوب' },
  { id: 'physics', value: 'الفيزياء العامة 1' },
  { id: 'Discrete Mathematics', value: 'رياضيات منفصلة' },
  { id: 'csBasics', value: 'أساسيات الحاسوب' },
  { id: 'statistics', value: 'مبادئ الإحصاء' },
  { id: 'chemistry', value: 'الكيمياء العامة 1' },
  { id: 'calculus1', value: 'تفاضل وتكامل 1' },
  { id: 'calculus2', value: 'تفاضل وتكامل 2' },
  { id: 'linearAlgebra', value: 'الجبر الخطي' },
  { id: 'calculus3', value: 'تفاضل وتكامل 3' },
  { id: 'probability', value: 'احتمالات ومتغيرات عشوائية' },
  { id: 'numericalAnalysisLab', value: 'التحليل العددي العملي' },
  { id: 'physicsLab1', value: 'الفيزيا العملية 1' },
  { id: 'physics2', value: 'الفيزياء العامة 2' },
  { id: 'electricCircuits', value: 'دارات كهربائية' },
  { id: 'physicsLab2', value: 'الفيزيا العملية 2' },
  { id: 'electronics1', value: 'الكترونيات 1' },
  { id: 'electricCircuitsLab', value: 'مختبر الدارات الكهربائية' },
  { id: 'signalsSystems', value: 'تحليل اشارات وانظمة' },
  { id: 'electricalMachines', value: 'الالات الكهربائية' },
  {
    id: 'digitalElectronicsVLSI',
    value: 'الاكترونيات الرقمية و دوائر التكامل الكبير جدا',
  },
  {
    id: 'digitalElectronicsVLSILab',
    value: 'مختبر الاكترونيات الرقمية و دوائر التكامل الكبير جدا',
  },
  { id: 'c++', value: 'المهارات الحاسوبية للمهندسين' },
  { id: 'digitalLogic', value: 'المنطق الرقمي' },
  { id: 'java', value: 'حل المشاكل بالبرمجة الشيئية' },
  { id: 'python', value: 'مختبر تطبيقات الحاسوب' },
  { id: 'softwareEngineering', value: 'هندسة البرمجيات (اختياري)' },
  { id: 'dataStructuresAlgorithms', value: 'تراكيب البيانات والخوارزميات' },
  { id: 'mobileComputing', value: 'حوسبة الهواتف الخلوية (اختياري)' },
  { id: 'databaseSystems', value: 'نظم قواعد البيانات' },
  { id: 'modernOperatingSystems', value: 'نظم التشغيل الحديثة' },
  { id: 'competitiveProgramming', value: 'البرمجة التنافسية (اختياري)' },
  { id: 'parallelProcessors', value: 'معالجات متوازية' },
  { id: 'parallelProcessorsLab', value: 'مختبر المعالجات المتوازية' },
  {
    id: 'digitalImageProcessing',
    value: 'تحليل ومعالجة الصور الرقمية (اختياري)',
  },
  { id: 'aiAndMachineLearning', value: 'الذكاء الاصطناعي وتعلم الالة' },
  { id: 'computerVision', value: 'رؤية الحاسوب (اختياري)' },
  { id: 'computationalIntelligence', value: 'الذكاء الحسابي (اختياري)' },
  { id: 'advancedMLTopics', value: 'مواضيع متقدمة في تعلم الالة (اختياري)' },
  { id: 'dataScience', value: 'علم البيانات (اختياري)' },

  { id: 'digitalLogicLab', value: 'مختبر المنطق الرقمي' },

  { id: 'computerArchitecture', value: '1 معمارية وتنظيم الحاسوب' },
  { id: 'advancedDigitalDesign', value: 'التصميم الرقمي المتقدم (اختياري)' },
  { id: 'design', value: 'معمارية وتنظيم الحاسوب 2' },
  { id: 'computerOrganizationLab', value: 'مختبر تنظيم الحاسوب' },

  { id: 'optimizedCompilers', value: 'المترجمات المحسنة الكفاءة (اختياري)' },
  { id: 'embeddedSystems', value: 'الانظمة المضمنة' },
  { id: 'computerNetworks', value: 'شبكات الحاسوب' },
  { id: 'embeddedSystemsLab', value: 'مختبر الانظمة المضمنة' },
  { id: 'internetOfThings', value: 'انترنت الاشياء (اختياري)' },
  { id: 'controlSystems', value: 'انظمة التحكم' },
  { id: 'mobileRobots', value: 'الروبوتات المتنقلة (اختياري)' },

  { id: 'wirelessNetworks', value: 'الشبكات الاسلكية (اختياري)' },
  { id: 'computerNetworksLab', value: 'مختبر شبكات الحاسوب' },
  { id: 'cloudComputing', value: 'الحوسبة السحابية(اختياري)' },
  { id: 'informationSecurity', value: 'امن المعلومات والشبكات' },
  { id: 'dataCommunicationSystems', value: 'أنظمة اتصالات البيانات' },
  {
    id: 'selectedTopicsInCE',
    value: 'مواضيع مختارة في هندسة الحاسوب(اختياري)',
  },
  { id: 'advancedNetworksLab', value: 'مختبر الشبكات المتقدم' },
  { id: 'networkProtocolsProgramming', value: 'برمجة بروتوكولات الشبكات' },
  { id: 'digitalForensics', value: 'الادلة الرقمية (اختياري)' },
];

export { staticValues };
