const staticValues = [
  { id: 'root', value: '2022 - الخطة الشجرية لهندسة الحاسوب' },
  { id: 'physics', value: 'الفيزياء العامة 1' },
  { id: 'Discrete Mathematics', value: 'رياضيات منفصلة' },
  { id: 'csBasics', value: 'أساسيات الحاسوب' },
  { id: 'statistics', value: 'مبادئ الإحصاء' },
  { id: 'chemistry', value: 'الكيمياء العامة 1' },
  { id: 'calculus1', value: 'تفاضل وتكامل 1' },
  { id: 'calculus2', value: 'تفاضل وتكامل 2' },
  { id: 'linearAlgebra', value: 'الجبر الخطي' },
  { id: 'calculus3', value: 'تفاضل وتكامل 3' },
  { id: 'probability', value: 'احتمالات ومتغيرات عشوائية' },
  { id: 'numericalAnalysisLab', value: 'التحليل العددي العملي' },
  { id: 'physicsLab1', value: 'الفيزيا العملية 1' },
  { id: 'physics2', value: 'الفيزياء العامة 2' },
  { id: 'electricCircuits', value: 'دارات كهربائية' },
  { id: 'physicsLab2', value: 'الفيزيا العملية 2' },
  { id: 'electronics1', value: 'الكترونيات 1' },
  { id: 'electricCircuitsLab', value: 'مختبر الدارات الكهربائية' },
  { id: 'signalsSystems', value: 'تحليل اشارات وانظمة' },
  { id: 'electricalMachines', value: 'الالات الكهربائية' },
  {
    id: 'digitalElectronicsVLSI',
    value: 'الاكترونيات الرقمية و دوائر التكامل الكبير جدا',
  },
  {
    id: 'digitalElectronicsVLSILab',
    value: 'مختبر الاكترونيات الرقمية و دوائر التكامل الكبير جدا',
  },
  { id: 'c++', value: 'المهارات الحاسوبية للمهندسين' },
  { id: 'digitalLogic', value: 'المنطق الرقمي' },
  { id: 'java', value: 'حل المشاكل بالبرمجة الشيئية' },
  { id: 'python', value: 'مختبر تطبيقات الحاسوب' },
  { id: 'softwareEngineering', value: 'هندسة البرمجيات (اختياري)' },
  { id: 'dataStructuresAlgorithms', value: 'تراكيب البيانات والخوارزميات' },
  { id: 'mobileComputing', value: 'حوسبة الهواتف الخلوية (اختياري)' },
  { id: 'databaseSystems', value: 'نظم قواعد البيانات' },
  { id: 'modernOperatingSystems', value: 'نظم التشغيل الحديثة' },
  { id: 'competitiveProgramming', value: 'البرمجة التنافسية (اختياري)' },
  { id: 'parallelProcessors', value: 'معالجات متوازية' },
  { id: 'parallelProcessorsLab', value: 'مختبر المعالجات المتوازية' },
  {
    id: 'digitalImageProcessing',
    value: 'تحليل ومعالجة الصور الرقمية (اختياري)',
  },
  { id: 'aiAndMachineLearning', value: 'الذكاء الاصطناعي وتعلم الالة' },
  { id: 'computerVision', value: 'رؤية الحاسوب (اختياري)' },
  { id: 'computationalIntelligence', value: 'الذكاء الحسابي (اختياري)' },
  { id: 'advancedMLTopics', value: 'مواضيع متقدمة في تعلم الالة (اختياري)' },
  { id: 'dataScience', value: 'علم البيانات (اختياري)' },

  { id: 'digitalLogicLab', value: 'مختبر المنطق الرقمي' },

  { id: 'computerArchitecture', value: '1 معمارية وتنظيم الحاسوب' },
  { id: 'advancedDigitalDesign', value: 'التصميم الرقمي المتقدم (اختياري)' },
  { id: 'design', value: 'معمارية وتنظيم الحاسوب 2' },
  { id: 'computerOrganizationLab', value: 'مختبر تنظيم الحاسوب' },

  { id: 'optimizedCompilers', value: 'المترجمات المحسنة الكفاءة (اختياري)' },
  { id: 'embeddedSystems', value: 'الانظمة المضمنة' },
  { id: 'computerNetworks', value: 'شبكات الحاسوب' },
  { id: 'embeddedSystemsLab', value: 'مختبر الانظمة المضمنة' },
  { id: 'internetOfThings', value: 'انترنت الاشياء (اختياري)' },
  { id: 'controlSystems', value: 'انظمة التحكم' },
  { id: 'mobileRobots', value: 'الروبوتات المتنقلة (اختياري)' },

  { id: 'wirelessNetworks', value: 'الشبكات الاسلكية (اختياري)' },
  { id: 'computerNetworksLab', value: 'مختبر شبكات الحاسوب' },
  { id: 'cloudComputing', value: 'الحوسبة السحابية(اختياري)' },
  { id: 'informationSecurity', value: 'امن المعلومات والشبكات' },
  { id: 'dataCommunicationSystems', value: 'أنظمة اتصالات البيانات' },
  {
    id: 'selectedTopicsInCE',
    value: 'مواضيع مختارة في هندسة الحاسوب(اختياري)',
  },
  { id: 'advancedNetworksLab', value: 'مختبر الشبكات المتقدم' },
  { id: 'networkProtocolsProgramming', value: 'برمجة بروتوكولات الشبكات' },
  { id: 'digitalForensics', value: 'الادلة الرقمية (اختياري)' },
];

const staticValues2 = [
  { id: 1, value: 'Physics' },
  { id: 2, value: 'Discrete Mathematics' },
  { id: 3, value: 'CS Basics' },
  { id: 4, value: 'Statistics' },
  { id: 5, value: 'Chemistry' },
  { id: 6, value: 'Calculus 1' },
  { id: 7, value: 'Calculus 2' },
  { id: 8, value: 'Linear Algebra' },
  { id: 9, value: 'Calculus 3' },
  { id: 10, value: 'Probability' },
  { id: 11, value: 'Numerical Analysis Lab' },
  { id: 12, value: 'Physics Lab 1' },
  { id: 13, value: 'Physics 2' },
  { id: 14, value: 'Electric Circuits' },
  { id: 15, value: 'Physics Lab 2' },
  { id: 16, value: 'Electronics 1' },
  { id: 17, value: 'Electric Circuits Lab' },
  { id: 18, value: 'Signals Systems' },
  { id: 19, value: 'Electrical Machines' },
  { id: 20, value: 'Digital Electronics VLSI' },
  { id: 21, value: 'Digital Electronics VLSI Lab' },
  { id: 22, value: 'C++' },
  { id: 23, value: 'Digital Logic' },
  { id: 24, value: 'Java' },
  { id: 25, value: 'Python' },
  { id: 26, value: 'Software Engineering' },
  { id: 27, value: 'Data Structures Algorithms' },
  { id: 28, value: 'Mobile Computing' },
  { id: 29, value: 'Database Systems' },
  { id: 30, value: 'Modern Operating Systems' },
  { id: 31, value: 'Competitive Programming' },
  { id: 32, value: 'Parallel Processors' },
  { id: 33, value: 'Parallel Processors Lab' },
  { id: 34, value: 'Digital Image Processing' },
  { id: 35, value: 'AI and Machine Learning' },
  { id: 36, value: 'Computer Vision' },
  { id: 37, value: 'Computational Intelligence' },
  { id: 38, value: 'Advanced ML Topics' },
  { id: 39, value: 'Data Science' },
  { id: 40, value: 'Digital Logic Lab' },
  { id: 41, value: 'Computer Architecture' },
  { id: 42, value: 'Advanced Digital Design' },
  { id: 43, value: 'Design' },
  { id: 44, value: 'Computer Organization Lab' },
  { id: 45, value: 'Optimized Compilers' },
  { id: 46, value: 'Embedded Systems' },
  { id: 47, value: 'Computer Networks' },
  { id: 48, value: 'Embedded Systems Lab' },
  { id: 49, value: 'Internet of Things' },
  { id: 50, value: 'Control Systems' },
  { id: 51, value: 'Mobile Robots' },
  { id: 52, value: 'Wireless Networks' },
  { id: 53, value: 'Computer Networks Lab' },
  { id: 54, value: 'Cloud Computing' },
  { id: 55, value: 'Information Security' },
  { id: 56, value: 'Data Communication Systems' },
  { id: 57, value: 'Selected Topics in CE' },
  { id: 58, value: 'Advanced Networks Lab' },
  { id: 59, value: 'Network Protocols Programming' },
  { id: 60, value: 'Digital Forensics' },
];

export { staticValues, staticValues2 };
