version: "3.9"

services:
  app:
    build: .
    container_name: fullstack_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postengmap
      SPRING_DATASOURCE_USERNAME: postengmap_user
      SPRING_DATASOURCE_PASSWORD: jkSoPuWvXKzMEs7EjEUM6u2I8eXb5AUx
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      PORT: 8080
