import { type Edge } from '@xyflow/react';

import { It_Sciences, computerStyle, ElectricityStyle } from './EdgeColor';

const initialEdgesEE: Edge[] = [
  {
    id: 'r-csRemedial',
    source: 'root',
    target: 'csRemedial',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'r-physics',
    source: 'root',
    target: 'physics',
    type: 'smoothstep',
    style: It_Sciences,
  },

  {
    id: 'r-calculus1',
    source: 'root',
    target: 'calculus1',
    type: 'smoothstep',
    style: It_Sciences,
  },
  //calculus1 pointer
  {
    id: 'calculus1-calculus2',
    source: 'calculus1',
    target: 'calculus2',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'calculus2-calculus3',
    source: 'calculus2',
    target: 'calculus3',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'calculus3-engineeringMath1',
    source: 'calculus3',
    target: 'engineeringMath1',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'engineeringMath1-signalsAndSystems',
    source: 'engineeringMath1',
    target: 'signalsAndSystems',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'signalsAndSystems-engineeringMath2',
    source: 'signalsAndSystems',
    target: 'engineeringMath2',
    type: 'smoothstep',
    style: ElectricityStyle,
  },

  // engineeringMath2 pointer
  {
    id: 'engineeringMath2-numericalMethods',
    source: 'engineeringMath2',
    target: 'numericalMethods',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'engineeringMath2-physics2_',
    source: 'engineeringMath2',
    target: 'physics2_',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'engineeringMath2-engineeringEconomy',
    source: 'engineeringMath2',
    target: 'engineeringEconomy',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  //numericalMethods  path
  {
    id: 'numericalMethods-controlSystems',
    source: 'numericalMethods',
    target: 'controlSystems',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'controlSystems-instrumentsAndControlLab',
    source: 'controlSystems',
    target: 'instrumentsAndControlLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'controlSystems-selectedTopicsControl',
    source: 'controlSystems',
    target: 'selectedTopicsControl',
    type: 'smoothstep',
    style: ElectricityStyle,
  },

  // physics2_ path
  {
    id: 'physics2_-electromagnetics1',
    source: 'physics2_',
    target: 'electromagnetics1',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electromagnetics1-electromagnetics2',
    source: 'electromagnetics1',
    target: 'electromagnetics2',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electromagnetics2-communications1',
    source: 'electromagnetics2',
    target: 'communications1',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electromagnetics2-antennasWavePropagation',
    source: 'electromagnetics2',
    target: 'antennasWavePropagation',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1-communicationSystems',
    source: 'communications1',
    target: 'communicationSystems',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  //physics path
  {
    id: 'physics-physicsLab1',
    source: 'physics',
    target: 'physicsLab1',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'physics-physics2',
    source: 'physics',
    target: 'physics2',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'physics2-physicsLab2',
    source: 'physics2',
    target: 'physicsLab2',
    type: 'smoothstep',
    style: It_Sciences,
  },
  {
    id: 'physics2-electricCircuits1',
    source: 'physics2',
    target: 'electricCircuits1',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  // electricCircuits1 path

  {
    id: 'electricCircuits1-electronics1',
    source: 'electricCircuits1',
    target: 'electronics1',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electricCircuits1-electricCircuits2',
    source: 'electricCircuits1',
    target: 'electricCircuits2',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electricCircuits1-signalsAndSystems_',
    source: 'electricCircuits1',
    target: 'signalsAndSystems_',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  // electronics1 path
  {
    id: 'electronics1-electronics2',
    source: 'electronics1',
    target: 'electronics2',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electronics2-engineeringEthics',
    source: 'electronics2',
    target: 'engineeringEthics',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electronics2-electronicsLab',
    source: 'electronics2',
    target: 'electronicsLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electronics2-digitalElectronics',
    source: 'electronics2',
    target: 'digitalElectronics',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  // digitalElectronics path

  {
    id: 'digitalElectronics-integratedCircuits',
    source: 'digitalElectronics',
    target: 'integratedCircuits',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'digitalElectronics-advancedElectronicsLab',
    source: 'digitalElectronics',
    target: 'advancedElectronicsLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'digitalElectronics-biomedicalElectronics',
    source: 'digitalElectronics',
    target: 'biomedicalElectronics',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electronics1-signalsAndSystems__',
    source: 'electronics1',
    target: 'signalsAndSystems__',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'signalsAndSystems__-powerElectronics',
    source: 'signalsAndSystems__',
    target: 'powerElectronics',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerElectronics-electricDrives',
    source: 'powerElectronics',
    target: 'electricDrives',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'signalsAndSystems-engineeringProbability',
    source: 'signalsAndSystems_',
    target: 'engineeringProbability',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'engineeringProbability-communications1_',
    source: 'engineeringProbability',
    target: 'communications1_',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1_-digitalElectronics_',
    source: 'communications1_',
    target: 'digitalElectronics_',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1_-communications2',
    source: 'communications1_',
    target: 'communications2',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1_-communicationNetworks',
    source: 'communications1_',
    target: 'communicationNetworks',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1_-digitalSignalProcessing',
    source: 'communications1_',
    target: 'digitalSignalProcessing',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1_-opticalCommunications',
    source: 'communications1_',
    target: 'opticalCommunications',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications1_-selectedTopicsControl_',
    source: 'communications1_',
    target: 'selectedTopicsControl_',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  //coummunications2 path
  {
    id: 'communications2-mobileCommunications',
    source: 'communications2',
    target: 'mobileCommunications',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications2-communicationsLab',
    source: 'communications2',
    target: 'communicationsLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications2-multimediaStreaming',
    source: 'communications2',
    target: 'multimediaStreaming',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'communications2-advancedCommunicationsLab',
    source: 'communications2',
    target: 'advancedCommunicationsLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electricCircuits2-electricCircuitsLab',
    source: 'electricCircuits2',
    target: 'electricCircuitsLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electricCircuits2-electricalMachines1',
    source: 'electricCircuits2',
    target: 'electricalMachines1',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electricalMachines1-electricalMachines2',
    source: 'electricalMachines1',
    target: 'electricalMachines2',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'electricalMachines1-powerSystemAnalysis',
    source: 'electricalMachines1',
    target: 'powerSystemAnalysis',
    type: 'smoothstep',
    style: ElectricityStyle,
  },

  {
    id: 'electricalMachines2-electricalMachinesLab',
    source: 'electricalMachines2',
    target: 'electricalMachinesLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },

  {
    id: 'powerSystemAnalysis-powerSystemProtection',
    source: 'powerSystemAnalysis',
    target: 'powerSystemProtection',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemAnalysis-selectedTopicsPower',
    source: 'powerSystemAnalysis',
    target: 'selectedTopicsPower',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemAnalysis-highVoltageEngineering',
    source: 'powerSystemAnalysis',
    target: 'highVoltageEngineering',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemAnalysis-powerSystemOperations',
    source: 'powerSystemAnalysis',
    target: 'powerSystemOperations',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemAnalysis-powerSystemPlanning',
    source: 'powerSystemAnalysis',
    target: 'powerSystemPlanning',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemAnalysis-renewableEnergyAndQuality',
    source: 'powerSystemAnalysis',
    target: 'renewableEnergyAndQuality',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemProtection-powerLab',
    source: 'powerSystemProtection',
    target: 'powerLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'powerSystemProtection-advancedPowerLab',
    source: 'powerSystemProtection',
    target: 'advancedPowerLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'csRemedial-csSkills',
    source: 'csRemedial',
    target: 'csSkills',
    type: 'smoothstep',
    style: computerStyle,
  },
  {
    id: 'csSkills-digitalLogic',
    source: 'csSkills',
    target: 'digitalLogic',
    type: 'smoothstep',
    style: computerStyle,
  },
  {
    id: 'digitalLogic-digitalLogicLab',
    source: 'digitalLogic',
    target: 'digitalLogicLab',
    type: 'smoothstep',
    style: computerStyle,
  },
  {
    id: 'digitalLogic-microprocessors',
    source: 'digitalLogic',
    target: 'microprocessors',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'microprocessors-microcontrollerApplications',
    source: 'microprocessors',
    target: 'microcontrollerApplications',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'microcontrollerApplications-microcontrollerApplicationsLab',
    source: 'microcontrollerApplications',
    target: 'microcontrollerApplicationsLab',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
  {
    id: 'microcontrollerApplications-computerApplications',
    source: 'microcontrollerApplications',
    target: 'computerApplications',
    type: 'smoothstep',
    style: ElectricityStyle,
  },
];

export { initialEdgesEE };
